# See here for image contents: https://hub.docker.com/r/frolvlad/alpine-miniconda3/dockerfile
FROM frolvlad/alpine-miniconda3

RUN echo "****** installing dev packages1 ******" && \
    echo "****** installing dev packages2 ******"


